### ISSUE TITLE
[Feature Request] handle การเปิดไฟล์ซับจากแอปอื่น

### ISSUE THREAD

**Issue by pureexe** [buftaku/Buftaku-Subtitle-Utility#3]
เมื่อเราดาวน์โหลดไฟล์ ass จากเน็ตแล้วเมื่อเปิดผ่านแอปดาวน์โหลดจะขึ้นว่าไม่สามารถเปิดไฟล์ได้ เนื่องจากไม่ได้ handle นามสกุลไฟล์ไว้

ภาพ 
![](https://www.img.in.th/images/45cd737f74dd1560261dafcbba0cd3ef.png)

อ่านรายละเอียดเพิ่มเติมได้ที่

https://stackoverflow.com/questions/3760276/android-intent-filter-associate-app-with-file-extension

**Comment by buftaku** [comment]
จากไฟล์ MainActivity.cs

`
[Activity(Label = "Buftaku Subtitle Utility", MainLauncher = true, Icon = "@drawable/Icon", ScreenOrientation = ScreenOrientation.Portrait)]
    [IntentFilter(new[]
        {
            Intent.ActionView
        },
    Categories = new[]
        {
            Intent.CategoryDefault,
            Intent.CategoryBrowsable
        },
    DataMimeType = "text/*",
    DataScheme = "file",
    DataHost = "*",
DataPathPatterns = new[] { @".*\\.ass", @".*\\.srt", @".*\\.vtt" })]
`

ปกติเวลาเลือกไฟล์นามสกุล .ass หรือ .srt หรือ .vtt Android จะค้นหาแอปที่รองรับไฟล์เหล่านี้ครับ ซึ่งแอปนี้ก็ได้ลงทะเบียนกับเครื่องไว้แล้วว่าตัวเองรองรับไฟล์นามสกุลแบบไหน ซึ่งถ้าหากแอปถูกเรียกจาก protocol แบบนั้นก็จะมีข้อมูลใน `Intent.Data.Path` ที่ไม่ใช่ null และเป็นที่อยู่ของไฟล์ครับ

หลังจากที่ MainActivity จัดการกับเนื้อหาในหน้าของมันแล้ว มันจะเช็คว่า `Intent.Data.Path` มีข้อมูลที่ไม่ใช่ null หรือเปล่า ถ้าเป็น null ก็จะเข้าหน้าปกติ แต่หากมีเนื้อหาข้างในอื่นๆ จะส่งที่อยู่ของไฟล์นั้นไปให้ Editor ไม่ว่าไฟล์มันจะมีจริง หรือที่อยู่จะผิดรูปแบบหรือยังไงก็ตาม

ซึ่งแอปดาวน์โหลดที่ติดมากับเครื่องที่ว่านี้มันแตกต่างกันไปแล้วแต่ละยี่ห้อและแต่ละ ROM 
อยากทราบว่าตอนเลือกเปิดไฟล์ซับไตเติ้ลที่ว่านั้น มี Buftaku Subtitle Utility ให้เลือกเปิดหรือไม่ครับ 
ถ้ามีให้เปิดแล้วแอปได้อ่านไฟล์แล้ว แอปมีขึ้นว่าอะไรหรือไม่ครับ

**Comment by buftaku** [comment]
จากที่ทราบมาคร่าวๆคือแอป Downloads ของแอนดรอยหลายๆเครื่องจะใช้เปิดไฟล์บางชนิดเช่น .apk ไม่ได้ครับ ถ้าลองเปิดไฟล์ .ass นั้นจาก File Browser ตัวอื่นอาจจะมีหน้าต่างเลือกแอปหลายๆตัวขึ้นมาให้ ซึ่งหนึ่งในนั้นควรจะมี Buftaku Subtitle Utility ครับ

**Comment by pureexe** [comment]
ลองจากตัว File Browser ของเครื่องมา ใช้ได้ น่าจะเป็นที่ตัวแอป Downloads เอง
